#pragma once

namespace Laser
{
	enum ClassID
	{
		CLASS_ID_COMMAND_CLEAR,
		CLASS_ID_COMMAND_SHADER,
		CLASS_ID_COMMAND_VERTEX_BUFFER,
		CLASS_ID_COMMAND_MATERIAL,
		CLASS_ID_COMMAND_RENDER_TARGET,
		CLASS_ID_COMMAND_RENDER_TARGET_RESET
	};
}
